version: "3.8"

services:
  web:
    image: neehar2601/compose-demo:latest
    ports:
      - "5002:5000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    # NEW: Mount the volume
    volumes:
      - redis-data:/data

# NEW: Define the volume at the top level
volumes:
  redis-data:
